/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example;

import javax.swing.*;

/**
 *
 * @author Dell_Suporte
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupQ1 = new javax.swing.ButtonGroup();
        buttonGroupQ2 = new javax.swing.ButtonGroup();
        buttonGroupQ3 = new javax.swing.ButtonGroup();
        buttonGroupQ4 = new javax.swing.ButtonGroup();
        buttonGroupQ5 = new javax.swing.ButtonGroup();
        buttonGroupQ6 = new javax.swing.ButtonGroup();
        buttonGroupQ7 = new javax.swing.ButtonGroup();
        buttonGroupQ8 = new javax.swing.ButtonGroup();
        buttonGroupQ9 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroupQ10 = new javax.swing.ButtonGroup();
        buttonGroupQ11 = new javax.swing.ButtonGroup();
        jLabelTitle = new javax.swing.JLabel();
        jLabelQ1 = new javax.swing.JLabel();
        jRadioButtonQ1com = new javax.swing.JRadioButton();
        jRadioButtonQ1res = new javax.swing.JRadioButton();
        jLabelQ2 = new javax.swing.JLabel();
        jRadioButtonQ2baixo = new javax.swing.JRadioButton();
        jRadioButtonQ2medio = new javax.swing.JRadioButton();
        jRadioButtonQ2alto = new javax.swing.JRadioButton();
        jLabelQ3 = new javax.swing.JLabel();
        jRadioButtonQ3baixo = new javax.swing.JRadioButton();
        jRadioButtonQ3medio = new javax.swing.JRadioButton();
        jRadioButtonQ3alto = new javax.swing.JRadioButton();
        jLabelQ4 = new javax.swing.JLabel();
        jRadioButtonQ4sim = new javax.swing.JRadioButton();
        jRadioButtonQ4nao = new javax.swing.JRadioButton();
        jLabelQ4sim = new javax.swing.JLabel();
        jLabelQ5 = new javax.swing.JLabel();
        jRadioButtonQ5sim = new javax.swing.JRadioButton();
        jRadioButtonQ5nao = new javax.swing.JRadioButton();
        jLabelQ5sim = new javax.swing.JLabel();
        jLabelQ6 = new javax.swing.JLabel();
        jRadioButtonQ6sim = new javax.swing.JRadioButton();
        jRadioButtonQ6nao = new javax.swing.JRadioButton();
        jLabelQ6sim = new javax.swing.JLabel();
        jLabelQ7 = new javax.swing.JLabel();
        jRadioButtonQ7sim = new javax.swing.JRadioButton();
        jRadioButtonQ7nao = new javax.swing.JRadioButton();
        jLabelQ7sim = new javax.swing.JLabel();
        jLabelQ8 = new javax.swing.JLabel();
        jRadioButtonQ8sim = new javax.swing.JRadioButton();
        jRadioButtonQ8nao = new javax.swing.JRadioButton();
        jLabelQ8sim = new javax.swing.JLabel();
        jLabelQ9 = new javax.swing.JLabel();
        jRadioButtonQ9sim = new javax.swing.JRadioButton();
        jRadioButtonQ9nao = new javax.swing.JRadioButton();
        jLabelQ9sim = new javax.swing.JLabel();
        jSpinnerTCP = new javax.swing.JSpinner();
        jSpinnerPorta = new javax.swing.JSpinner();
        jSpinnerAntena = new javax.swing.JSpinner();
        jSpinnerCatraca = new javax.swing.JSpinner();
        jSpinnerFacial = new javax.swing.JSpinner();
        jSpinnerMobile = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelQ12 = new javax.swing.JLabel();
        jRadioButtonQ12sim = new javax.swing.JRadioButton();
        jRadioButtonQ12nao = new javax.swing.JRadioButton();
        jLabelQ10 = new javax.swing.JLabel();
        jRadioButtonQ10sim = new javax.swing.JRadioButton();
        jRadioButtonQ10nao = new javax.swing.JRadioButton();
        jLabelQ10sim = new javax.swing.JLabel();
        jSpinnerClients = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        selecionarButtonNao();
        esconderSpinners();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitle.setText("Questionário para máquina MTG");

        jLabelQ1.setText("Qual é o tipo do condomínio ?");

        buttonGroupQ1.add(jRadioButtonQ1com);
        jRadioButtonQ1com.setText("Comercial");
        jRadioButtonQ1com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ1comActionPerformed(evt);
            }
        });

        buttonGroupQ1.add(jRadioButtonQ1res);
        jRadioButtonQ1res.setText("Residencial");
        jRadioButtonQ1res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ1resActionPerformed(evt);
            }
        });

        jLabelQ2.setText("Quantos condôminos e funcionários ?");

        buttonGroupQ2.add(jRadioButtonQ2baixo);
        jRadioButtonQ2baixo.setText("Abaixo de 200");
        jRadioButtonQ2baixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ2baixoActionPerformed(evt);
            }
        });

        buttonGroupQ2.add(jRadioButtonQ2medio);
        jRadioButtonQ2medio.setText("Entre 200 e 700");
        jRadioButtonQ2medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ2medioActionPerformed(evt);
            }
        });

        buttonGroupQ2.add(jRadioButtonQ2alto);
        jRadioButtonQ2alto.setText("Acima de 700");
        jRadioButtonQ2alto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ2altoActionPerformed(evt);
            }
        });

        jLabelQ3.setText("Qual o fluxo de visitantes/prestadores ?");

        buttonGroupQ3.add(jRadioButtonQ3baixo);
        jRadioButtonQ3baixo.setText("Baixo");
        jRadioButtonQ3baixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ3baixoActionPerformed(evt);
            }
        });

        buttonGroupQ3.add(jRadioButtonQ3medio);
        jRadioButtonQ3medio.setText("Médio");
        jRadioButtonQ3medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ3medioActionPerformed(evt);
            }
        });

        buttonGroupQ3.add(jRadioButtonQ3alto);
        jRadioButtonQ3alto.setText("Alto");
        jRadioButtonQ3alto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ3altoActionPerformed(evt);
            }
        });

        jLabelQ4.setText("Possui equipamentos TCP ?");

        buttonGroupQ4.add(jRadioButtonQ4sim);
        jRadioButtonQ4sim.setText("Sim");
        jRadioButtonQ4sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ4simActionPerformed(evt);
            }
        });

        buttonGroupQ4.add(jRadioButtonQ4nao);
        jRadioButtonQ4nao.setText("Não");
        jRadioButtonQ4nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ4naoActionPerformed(evt);
            }
        });

        jLabelQ4sim.setText("Se sim, quantos ?");

        jLabelQ5.setText("Possui equipamentos do tipo Porta ?");

        buttonGroupQ5.add(jRadioButtonQ5sim);
        jRadioButtonQ5sim.setText("Sim");
        jRadioButtonQ5sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ5simActionPerformed(evt);
            }
        });

        buttonGroupQ5.add(jRadioButtonQ5nao);
        jRadioButtonQ5nao.setText("Não");
        jRadioButtonQ5nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ5naoActionPerformed(evt);
            }
        });

        jLabelQ5sim.setText("Se sim, quantos ?");

        jLabelQ6.setText("Possui equipamentos do tipo Antena ?");

        buttonGroupQ6.add(jRadioButtonQ6sim);
        jRadioButtonQ6sim.setText("Sim");
        jRadioButtonQ6sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ6simActionPerformed(evt);
            }
        });

        buttonGroupQ6.add(jRadioButtonQ6nao);
        jRadioButtonQ6nao.setText("Não");
        jRadioButtonQ6nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ6naoActionPerformed(evt);
            }
        });

        jLabelQ6sim.setText("Se sim, quantos ?");

        jLabelQ7.setText("Possui equipamentos do tipo Catraca ?");

        buttonGroupQ7.add(jRadioButtonQ7sim);
        jRadioButtonQ7sim.setText("Sim");
        jRadioButtonQ7sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ7simActionPerformed(evt);
            }
        });

        buttonGroupQ7.add(jRadioButtonQ7nao);
        jRadioButtonQ7nao.setText("Não");
        jRadioButtonQ7nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ7naoActionPerformed(evt);
            }
        });

        jLabelQ7sim.setText("Se sim, quantos ?");

        jLabelQ8.setText("Possui equipamentos do tipo Facial ?");

        buttonGroupQ8.add(jRadioButtonQ8sim);
        jRadioButtonQ8sim.setText("Sim");
        jRadioButtonQ8sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ8simActionPerformed(evt);
            }
        });

        buttonGroupQ8.add(jRadioButtonQ8nao);
        jRadioButtonQ8nao.setText("Não");
        jRadioButtonQ8nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ8naoActionPerformed(evt);
            }
        });

        jLabelQ8sim.setText("Se sim, quantos ?");

        jLabelQ9.setText("Possui o nosso Aplicativo MTGMobile ?");

        buttonGroupQ9.add(jRadioButtonQ9sim);
        jRadioButtonQ9sim.setText("Sim");
        jRadioButtonQ9sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ9simActionPerformed(evt);
            }
        });

        buttonGroupQ9.add(jRadioButtonQ9nao);
        jRadioButtonQ9nao.setText("Não");
        jRadioButtonQ9nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ9naoActionPerformed(evt);
            }
        });

        jLabelQ9sim.setText("Se sim, quantos logins ?");

        jLabel1.setText("Responda o questionário abaixo para obter uma recomendação de máquina Servidora adequada");

        jButton1.setLabel("Obter recomendação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelQ12.setText("A máquina será de uso exclusivo ?");

        buttonGroupQ10.add(jRadioButtonQ12sim);
        jRadioButtonQ12sim.setText("Sim");
        jRadioButtonQ12sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ12simActionPerformed(evt);
            }
        });

        buttonGroupQ10.add(jRadioButtonQ12nao);
        jRadioButtonQ12nao.setText("Não");
        jRadioButtonQ12nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ12naoActionPerformed(evt);
            }
        });

        jLabelQ10.setText("Possui quantas máquinas Clients  ?");

        buttonGroupQ11.add(jRadioButtonQ10sim);
        jRadioButtonQ10sim.setText("Sim");
        jRadioButtonQ10sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ10simActionPerformed(evt);
            }
        });

        buttonGroupQ11.add(jRadioButtonQ10nao);
        jRadioButtonQ10nao.setText("Não");
        jRadioButtonQ10nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonQ10naoActionPerformed(evt);
            }
        });

        jLabelQ10sim.setText("Se sim, quantos ?");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Defina o uso da máquina!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelQ1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelQ2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelQ3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jRadioButtonQ3baixo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jRadioButtonQ3medio)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButtonQ3alto)
                                            .addGap(6, 6, 6))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jRadioButtonQ1com)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButtonQ1res))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonQ6sim)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonQ6nao))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jRadioButtonQ8sim)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonQ8nao)
                                            .addGap(114, 114, 114))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelQ8sim)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jSpinnerFacial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelQ6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelQ6sim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSpinnerAntena, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelQ4sim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSpinnerTCP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonQ4sim)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButtonQ4nao))
                                            .addComponent(jLabelQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17))))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelQ10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButtonQ10sim)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButtonQ10nao))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelQ10sim)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jSpinnerClients, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jRadioButtonQ2baixo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonQ2medio))
                                    .addComponent(jLabelQ8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelQ9)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jRadioButtonQ9sim)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jRadioButtonQ9nao)))
                                                    .addGap(40, 40, 40))
                                                .addComponent(jLabelQ7)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jRadioButtonQ7sim)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jRadioButtonQ7nao)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonQ5sim)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButtonQ5nao))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelQ5sim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSpinnerPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelQ7sim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSpinnerCatraca, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelQ9sim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSpinnerMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelQ12)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButtonQ12sim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonQ12nao))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonQ2alto)
                                        .addGap(101, 101, 101))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabelQ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonQ1res)
                    .addComponent(jRadioButtonQ1com))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelQ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonQ2baixo)
                    .addComponent(jRadioButtonQ2alto)
                    .addComponent(jRadioButtonQ2medio))
                .addGap(17, 17, 17)
                .addComponent(jLabelQ3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonQ3baixo)
                    .addComponent(jRadioButtonQ3alto)
                    .addComponent(jRadioButtonQ3medio))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelQ10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonQ10sim)
                            .addComponent(jRadioButtonQ10nao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQ10sim)
                            .addComponent(jSpinnerClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabelQ4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonQ4nao)
                            .addComponent(jRadioButtonQ4sim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQ4sim)
                            .addComponent(jSpinnerTCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabelQ6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonQ6sim)
                            .addComponent(jRadioButtonQ6nao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQ6sim)
                            .addComponent(jSpinnerAntena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelQ5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonQ5sim)
                                    .addComponent(jRadioButtonQ5nao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelQ5sim)
                                    .addComponent(jSpinnerPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelQ7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonQ7sim)
                                    .addComponent(jRadioButtonQ7nao))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQ7sim)
                            .addComponent(jSpinnerCatraca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabelQ9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonQ9sim)
                            .addComponent(jRadioButtonQ9nao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQ9sim)
                            .addComponent(jSpinnerMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelQ12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonQ12sim)
                            .addComponent(jRadioButtonQ12nao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelQ8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonQ8sim)
                            .addComponent(jRadioButtonQ8nao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQ8sim)
                            .addComponent(jSpinnerFacial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void esconderSpinners(){

        jSpinnerTCP.setVisible(false);
        jSpinnerPorta.setVisible(false);
        jSpinnerAntena.setVisible(false);
        jSpinnerCatraca.setVisible(false);
        jSpinnerFacial.setVisible(false);
        jSpinnerMobile.setVisible(false);
        jSpinnerClients.setVisible(false);

    }

    public void selecionarButtonNao(){
        jRadioButtonQ4nao.setSelected(true);
        jRadioButtonQ5nao.setSelected(true);
        jRadioButtonQ6nao.setSelected(true);
        jRadioButtonQ7nao.setSelected(true);
        jRadioButtonQ8nao.setSelected(true);
        jRadioButtonQ9nao.setSelected(true);
        jRadioButtonQ10nao.setSelected(true);
    }
    private void jRadioButtonQ1comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ1comActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQ1comActionPerformed

    private void jRadioButtonQ1resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ1resActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQ1resActionPerformed

    private void jRadioButtonQ2baixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ2baixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQ2baixoActionPerformed

    private void jRadioButtonQ3altoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ3altoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQ3altoActionPerformed

    private void jRadioButtonQ2altoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ2altoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQ2altoActionPerformed

    private void jRadioButtonQ3baixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ3baixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQ3baixoActionPerformed

    private void jRadioButtonQ2medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ2medioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQ2medioActionPerformed

    private void jRadioButtonQ3medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ3medioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonQ3medioActionPerformed

    private void jRadioButtonQ4naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ4naoActionPerformed
        jSpinnerTCP.setVisible(false);
    }//GEN-LAST:event_jRadioButtonQ4naoActionPerformed

    private void jRadioButtonQ5simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ5simActionPerformed
        jSpinnerPorta.setVisible(true);
    }//GEN-LAST:event_jRadioButtonQ5simActionPerformed

    private void jRadioButtonQ5naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ5naoActionPerformed
        jSpinnerPorta.setVisible(false);
    }//GEN-LAST:event_jRadioButtonQ5naoActionPerformed

    private void jRadioButtonQ6simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ6simActionPerformed
        jSpinnerAntena.setVisible(true);
    }//GEN-LAST:event_jRadioButtonQ6simActionPerformed

    private void jRadioButtonQ6naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ6naoActionPerformed
        jSpinnerAntena.setVisible(false);
    }//GEN-LAST:event_jRadioButtonQ6naoActionPerformed

    private void jRadioButtonQ7simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ7simActionPerformed
        jSpinnerCatraca.setVisible(true);
    }//GEN-LAST:event_jRadioButtonQ7simActionPerformed

    private void jRadioButtonQ7naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ7naoActionPerformed
        jSpinnerCatraca.setVisible(false);
    }//GEN-LAST:event_jRadioButtonQ7naoActionPerformed

    private void jRadioButtonQ8simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ8simActionPerformed
        jSpinnerFacial.setVisible(true);
    }//GEN-LAST:event_jRadioButtonQ8simActionPerformed

    private void jRadioButtonQ8naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ8naoActionPerformed
        jSpinnerFacial.setVisible(false);
    }//GEN-LAST:event_jRadioButtonQ8naoActionPerformed

    private void jRadioButtonQ9simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ9simActionPerformed
        jSpinnerMobile.setVisible(true);
    }//GEN-LAST:event_jRadioButtonQ9simActionPerformed

    private void jRadioButtonQ9naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ9naoActionPerformed
        jSpinnerMobile.setVisible(false);
    }//GEN-LAST:event_jRadioButtonQ9naoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(!jRadioButtonQ12sim.isSelected() && !jRadioButtonQ12nao.isSelected()){
            javax.swing.JOptionPane.showMessageDialog(this,"DEFINA O USO DA MÁQUINA","ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }else{
            String categoria;
            if (resultado() < 35){
                categoria = "C";
            }else if (resultado() > 35 && resultado() < 60){
                categoria = "B";
            }else{
                categoria = "A";
            }

            String text = "<html> Para esse projeto a máquina recomendada é: <b> <font color=\"green\"><font size=\"5\">" + categoria + "</font></font color> </b> \n Pontuação: " + resultado() ;
            javax.swing.JOptionPane.showMessageDialog(this,text);
            System.out.println(resultado());

        }





    }//GEN-LAST:event_jButton1ActionPerformed

    public int resultado(){
        int resultado = 0;

        //Pergunta para tipo de condomínio
        if(jRadioButtonQ1com.isSelected()){
            resultado += 15;
        } else if (jRadioButtonQ1res.isSelected()) {
            resultado += 5;
        }

        //Pergunta para quantidade de cond/func
        if(jRadioButtonQ2baixo.isSelected()){
            resultado += 5;
        } else if (jRadioButtonQ2medio.isSelected()) {
            resultado += 10;
        } else if (jRadioButtonQ2alto.isSelected()) {
            resultado += 15;
        }

        //Pergunta para quantidade de visitante/prestadores
        if(jRadioButtonQ3baixo.isSelected()){
            resultado += 5;
        }
        else if(jRadioButtonQ3medio.isSelected()){
            resultado += 10;
        }
        else if(jRadioButtonQ3alto.isSelected()){
            resultado += 15;
        }

        //Pergunta para máquinas clients
        if(jRadioButtonQ10sim.isSelected()){
            int value = (int)jSpinnerClients.getValue();
            resultado += value * 2;
        } else if (jRadioButtonQ10nao.isSelected()) {
            resultado += 0;
        }


        //Pergunta para equipamentos TCP
        if(jRadioButtonQ4sim.isSelected()){
            int value = (int)jSpinnerTCP.getValue();
            resultado += value * 2;
        }else if (jRadioButtonQ4nao.isSelected()){
            resultado += 0;
        }

        //Pergunta para equipamentos do tipo Antena
        if(jRadioButtonQ6sim.isSelected()){
            int value = (int)jSpinnerAntena.getValue();
            resultado += value * 2;
        }else if (jRadioButtonQ6nao.isSelected()){
            resultado += 0;
        }

        //Pergunta para equipamento do tipo facial
        if(jRadioButtonQ8sim.isSelected()){
            int value = (int)jSpinnerFacial.getValue();
            resultado += value * 2;
        }else if (jRadioButtonQ8nao.isSelected()){
            resultado += 0;
        }

        //Pergunta para equipamento do tipo porta
        if(jRadioButtonQ5sim.isSelected()){
            int value = (int)jSpinnerPorta.getValue();
            resultado += value * 2;
        } else if (jRadioButtonQ5nao.isSelected()) {
            resultado += 0;
        }

        //Pergunta para equipamento do tipo Catraca
        if(jRadioButtonQ7sim.isSelected()){
            int value = (int)jSpinnerCatraca.getValue();
            resultado += value * 2;
        } else if (jRadioButtonQ7nao.isSelected()) {
            resultado += 0;
        }

        //Pergunta para logins Mobile
        if(jRadioButtonQ9sim.isSelected()){
            int value = (int)jSpinnerMobile.getValue();
            resultado += value /50 ;
        } else if (jRadioButtonQ9nao.isSelected()) {
            resultado += 0;
        }

        //Pergunta para uso exclusivo
        if(jRadioButtonQ12sim.isSelected()){
            resultado += 0;
        } else if (jRadioButtonQ12nao.isSelected()) {
            resultado += 30;
        }

        return resultado;
    }


    private void jRadioButtonQ12simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ12simActionPerformed

    }//GEN-LAST:event_jRadioButtonQ12simActionPerformed

    private void jRadioButtonQ12naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ12naoActionPerformed
    }//GEN-LAST:event_jRadioButtonQ12naoActionPerformed

    private void jRadioButtonQ10simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ10simActionPerformed
        jSpinnerClients.setVisible(true);
    }//GEN-LAST:event_jRadioButtonQ10simActionPerformed

    private void jRadioButtonQ10naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ10naoActionPerformed
        jSpinnerClients.setVisible(false);
    }//GEN-LAST:event_jRadioButtonQ10naoActionPerformed

    private void jRadioButtonQ4simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonQ4simActionPerformed
        jSpinnerTCP.setVisible(true);
    }//GEN-LAST:event_jRadioButtonQ4simActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupQ1;
    private javax.swing.ButtonGroup buttonGroupQ10;
    private javax.swing.ButtonGroup buttonGroupQ11;
    private javax.swing.ButtonGroup buttonGroupQ2;
    private javax.swing.ButtonGroup buttonGroupQ3;
    private javax.swing.ButtonGroup buttonGroupQ4;
    private javax.swing.ButtonGroup buttonGroupQ5;
    private javax.swing.ButtonGroup buttonGroupQ6;
    private javax.swing.ButtonGroup buttonGroupQ7;
    private javax.swing.ButtonGroup buttonGroupQ8;
    private javax.swing.ButtonGroup buttonGroupQ9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelQ1;
    private javax.swing.JLabel jLabelQ10;
    private javax.swing.JLabel jLabelQ10sim;
    private javax.swing.JLabel jLabelQ12;
    private javax.swing.JLabel jLabelQ2;
    private javax.swing.JLabel jLabelQ3;
    private javax.swing.JLabel jLabelQ4;
    private javax.swing.JLabel jLabelQ4sim;
    private javax.swing.JLabel jLabelQ5;
    private javax.swing.JLabel jLabelQ5sim;
    private javax.swing.JLabel jLabelQ6;
    private javax.swing.JLabel jLabelQ6sim;
    private javax.swing.JLabel jLabelQ7;
    private javax.swing.JLabel jLabelQ7sim;
    private javax.swing.JLabel jLabelQ8;
    private javax.swing.JLabel jLabelQ8sim;
    private javax.swing.JLabel jLabelQ9;
    private javax.swing.JLabel jLabelQ9sim;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButtonQ10nao;
    private javax.swing.JRadioButton jRadioButtonQ10sim;
    private javax.swing.JRadioButton jRadioButtonQ12nao;
    private javax.swing.JRadioButton jRadioButtonQ12sim;
    private javax.swing.JRadioButton jRadioButtonQ1com;
    private javax.swing.JRadioButton jRadioButtonQ1res;
    private javax.swing.JRadioButton jRadioButtonQ2alto;
    private javax.swing.JRadioButton jRadioButtonQ2baixo;
    private javax.swing.JRadioButton jRadioButtonQ2medio;
    private javax.swing.JRadioButton jRadioButtonQ3alto;
    private javax.swing.JRadioButton jRadioButtonQ3baixo;
    private javax.swing.JRadioButton jRadioButtonQ3medio;
    private javax.swing.JRadioButton jRadioButtonQ4nao;
    private javax.swing.JRadioButton jRadioButtonQ4sim;
    private javax.swing.JRadioButton jRadioButtonQ5nao;
    private javax.swing.JRadioButton jRadioButtonQ5sim;
    private javax.swing.JRadioButton jRadioButtonQ6nao;
    private javax.swing.JRadioButton jRadioButtonQ6sim;
    private javax.swing.JRadioButton jRadioButtonQ7nao;
    private javax.swing.JRadioButton jRadioButtonQ7sim;
    private javax.swing.JRadioButton jRadioButtonQ8nao;
    private javax.swing.JRadioButton jRadioButtonQ8sim;
    private javax.swing.JRadioButton jRadioButtonQ9nao;
    private javax.swing.JRadioButton jRadioButtonQ9sim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAntena;
    private javax.swing.JSpinner jSpinnerCatraca;
    private javax.swing.JSpinner jSpinnerClients;
    private javax.swing.JSpinner jSpinnerFacial;
    private javax.swing.JSpinner jSpinnerMobile;
    private javax.swing.JSpinner jSpinnerPorta;
    private javax.swing.JSpinner jSpinnerTCP;
    // End of variables declaration//GEN-END:variables
}
